- components/graphs/TrackerGraph.vue
- components/graphs/TwitterOverview.vue
- components/graphs/UberOverview.vue
The graphs component did not call the `drawViz` function when the values change. It's fixed by using a `watch` property. Keep in mind for future graph components.
Close #173
> fix: graphs not updated when switching file (#173)

- components/TheDataExperience.vue
- components/TheDataExperienceDefault.vue
- manifests/experiences/explorer/explorer.json
- manifests/index.js
Addressing #188.
Added a key `showDataExplorer` to the manifest of each experience, controlling whether the data explorer component is shown at the bottom of the page or not.
The default value is true.
> feat: allow configuring whether to show data explorer for each experience

- components/TheDataExperience.vue
- components/TheDataExperienceDefault.vue
- manifests/README.md
- manifests/experiences/tracker-control/index.js
- manifests/experiences/tracker-control/pipeline.js
- manifests/experiences/tracker-control/tracker-control.json
- manifests/experiences/twitter/index.js
- manifests/experiences/twitter/pipeline.js
- manifests/experiences/twitter/twitter.json
- manifests/experiences/uber/index.js
- manifests/experiences/uber/pipeline.js
- manifests/experiences/uber/uber.json
This will be necessary because we are soon going to replace twitter experiences, using custom pipelines instead of sparql pipelines
> feat: each experience can have a different custom pipeline

- components/UnitCsvViewer.vue
- components/UnitFileExplorer.vue
- components/UnitJsonViewer.vue
- utils/file.js
Fixes bug #202 
Makes part of the refactoring needed for #203 
The logic of file extraction and building of a file tree has been moved from `components/UnitFileViewer.vue` to `utils/file.js`.
Created a class that could maybe handle everything file-related in the future.
> Fixed file tree in UnitFileViewer

- components/UnitCustomPipeline.vue
I didn't manage to show the progress circle on the button like for sparql. It would be nice if someone knows why
Note: I removed this part
```
computed: {
disabled() {
return !this.fileManager.preprocessedTexts
}
}
```
for two reasons:
- It's always false because preprocessedTexts is initialized as an empty object
- Even if the value changed, I'm not sure if vue would detect it (see [reactivity in depth](https://vuejs.org/v2/guide/reactivity.html))
> feat: put back run buttons for custom pipelines

- components/TheAppBar.vue
- components/TheDataExperienceList.vue
- layouts/default.vue
- layouts/error.vue
- manifests/index.js
- pages/_key.vue
- pages/index.vue
- store/index.js
* fixed #218, added a navigation guard middleware to `pages/_key.vue`
* moved `enabledExperiences`/`disabledExperiences` to the Vuex store
* improved newsletter code, better to keep code in `<script>` and `<template>` as clean as possible
* changed config loading to load the config in `manifests/index.js`
* added experience filter in `manifests/index.js` based on the config
> fix: #218 and various

- babel.config.json
- components/UnitFilterableTable.vue
- components/__tests__/UnitFilterableTable.test.js
- jest.setup.js
- package-lock.json
- package.json
- utils/csv.test.js
This PR aims at setting up a way of writing and running tests easily. It consists of the following additions:
- Add [Jest](https://jestjs.io/) for running test suites with `npm run test`.
- Unit tests on `.js` files can be written using Jest. An example is available in [utils/csv.test.js](https://github.com/hestiaAI/hestialabs-experiences/blob/test/unit-tests/utils/csv.test.js)
- Unit tests on components can be written with the help of Jest and [Vue test utils](https://vue-test-utils.vuejs.org/). An example is available in [components/\_\_tests\_\_/UnitFilterableTable.test.js](https://github.com/hestiaAI/hestialabs-experiences/blob/test/unit-tests/components/__tests__/UnitFilterableTable.test.js). It shows how to mount a component, mock the vuex store, and find specific HTML elements. …
> Framework for writing tests

- components/unit/consent-form/UnitConsentForm.vue
- components/unit/consent-form/UnitConsentFormSection.vue
- components/unit/files/UnitFiles.vue
- config/README.md
- config/config.json
- config/digipower.json
- config/workshop.json
Added support for text input fields in the consent form. Also removed `saveFiles` parameter that is no longer usable since the `fileManager` refactoring.
> feat: consent form upgrade

- components/chart/ChartView.vue
- components/unit/UnitVegaViz.vue
Addressing #241 
The problem is related to how `UnitVegaViz` and `ChartView` handle the given data when it's malformed or empty.
Changes:
- the error message now depends on whether the data is in the correct shape or if it is empty
- removed references to the vega graph when it doesn't exist in `UnitVegaViz`
Please give feedback if you see another way to solve this issue!
> fix: unitvegaviz and chartview dont crash when theres no data

- components/base/button/download/BaseButtonDownload.vue
- components/unit/file-explorer/UnitFileExplorer.vue
The file viewer for unknown types allows to download files only in firefox. Chrome tries to display even binary files.
This pull request adds a download option for all files, including those of a known type.
It contributes to address the feature request hestiaAI/digipower-data-experiences#79
> feat: add download button in file explorer 

- utils/file-manager.js
For some reason, in some zip archives, the folders are encoded as a file, which messes up the file explorer tree, so we observe empty files like this one:
After the fix, this file doesn't appear:
> fix: file explorer does not show an empty file corresponding to the folder itself

- utils/json.js
Is part of a solution for 
- https://github.com/hestiaAI/digipower-data-experiences/issues/66
> performance: (jsonviewer) lists are now split into groups of 50 elements

- components/the-data-experience/TheDataExperience.vue
- components/the-data-experience/TheDataExperienceDefault.vue
- components/unit/files/UnitFiles.vue
- manifests/experiences/apple/apple.json
- manifests/experiences/bookbeat/bookbeat.json
- manifests/experiences/finnair/finnair.json
- manifests/experiences/gigantti/gigantti.json
- manifests/experiences/helsingin-sanomat/helsingin-sanomat.json
- manifests/experiences/hsl/hsl.json
- manifests/experiences/k-ryhma/k-ryhma.json
- manifests/experiences/lime/lime.json
- manifests/experiences/linkedin/linkedin.json
- manifests/experiences/netflix/netflix.json
- manifests/experiences/s-ryhma/s-ryhma.json
- manifests/experiences/signal/signal.json
- manifests/experiences/spotify/spotify.json
- manifests/experiences/voi/voi.json
- manifests/experiences/whatsapp/whatsapp.json
- manifests/experiences/wolt/wolt.json
- utils/file-manager.js
Changes: 
- Fix `file-manager` for multiple files (now it doesn't remove the topmost path element when there are multiple files)
- Fix Uppy restrictions
- Generic experiences are configured to allow multiple files, others are not
- Change information message about file extensions and number of files
- Uppy box is a bit smaller
Related to:
- https://github.com/hestiaAI/digipower-data-experiences/issues/62
- https://github.com/hestiaAI/digipower-data-experiences/issues/59 point 6 within experiences
> fix: various fixes regarding file upload

- components/unit/consent-form/UnitConsentForm.vue
- pages/import.vue
This is a basic and manual way of dealing with the fact that the structure of the forms may change over time, which would break the import of older ZIPs
https://github.com/hestiaAI/digipower-data-experiences/issues/92
> feat: add form version control

- components/unit/filterable-table/UnitFilterableTable.vue
Related to https://github.com/hestiaAI/digipower-data-experiences/issues/85
Previously, the download button used the raw csv and not the actual displayed data.
> fix: the download button apply for the additional columns that we add/transform ourselves

- .eslintrc.js
- components/unit/file-explorer/UnitFileExplorer.vue
- components/unit/file-explorer/viewer/UnitFileExplorerViewerCsv.vue
- components/unit/file-explorer/viewer/UnitFileExplorerViewerJson.vue
- vuetify.options.js
Edit: PR is ready.
This is a work-in-progress PR that I think should be passed to @valentinoli or @andreaskundig as I'm not very familiar with UI development.
The main idea is that we would like to make the file explorer easier to navigate, and to save screen space by hiding the file selector when a file is selected.
The current changes are:
- moved the file selector inside a `VNavigationDrawer` component that is contained within the card of the file explorer.
- the layout is not great yet, and Alex suggested making the "mini" version of the drawer more compact by only showing the name of the current file or something more relevant than the whole tree
- changed the json viewer to display key-value pairs close by, instead of showing the values on the right-hand side
Changes:
- moved the …
> style: change file explorer layout

- components/unit/consent-form/UnitConsentForm.vue
- utils/utils.js
It may not work, but we are forced to deploy it on the test instance to see if it does. Now the filename would include the experience name and human-readable date
Related:
- https://github.com/hestiaAI/digipower-data-experiences/issues/105
- https://github.com/hestiaAI/digipower-data-experiences/issues/35
> fix: attempt at renaming blob

- components/unit/file-explorer/UnitFileExplorer.vue
Addressing most of the comments in:
- (https://github.com/hestiaAI/digipower-data-experiences/issues/71)
- (https://github.com/hestiaAI/digipower-data-experiences/issues/74)
Changes:
- summary of files:
- bold font to file type and number of occurrences
- capitalized extensions
- italicized file names
- changed list format (more compact and simple)
- `data points -> lines` for text files
- `data points -> datapoints` elsewhere
- summary doesn't disappear when a file is selected
- left panel:
- search box always appears at the top
- `100% -> 80%` width 
- clicking on selected file unselects it
Some problems that remain (but that could be solved in a following PR):
- summary of files:
- path of files could be shortened, but we cannot keep just the file name since we'll have duplicates (e.g. …
> style: improved file explorer summary string and left panel

- package-lock.json
- package.json
When updating @nuxtjs/vuetify (https://github.com/hestiaAI/hestialabs-experiences/commit/cbd1d8e4c311449dbb1392421bbf29c078541936), sass-loader has been updated automatically. But this version of sass-loader requires webpack 5, which we are not yet using, so I'm downgrading it for now.
> fix: latest sass-loader requires webpack 5

- components/TheAppBar.vue
- components/the-data-experience/TheDataExperienceDefault.vue
- components/unit/consent-form/UnitConsentForm.vue
- components/unit/consent-form/UnitConsentFormSection.vue
- components/unit/file-explorer/UnitFileExplorer.vue
- pages/import.vue
- store/index.js
Instead of having checkboxes in the file-explorer experience, we can open a dialog from the consent form. This dialog contains a file-explorer with checkboxes.
https://github.com/hestiaAI/digipower-data-experiences/issues/111
TODO:
- When we open a file that takes a lot of vertical space (e.g. an unwrapped json or an image) and open the navigation drawer, then the component does not shrink, it just shows blank space where the file was shown. (This was already the case before this PR)
> feat: select files in consent form

- components/unit/file-explorer/UnitFileExplorer.vue
…since it causes crashes on the file explorer.
For me, on Google Chrome, this solved the crashes with Anaelle's facebook zip but not with Charles'.
> fix: removed computation of the number of data points temporarily

- components/unit/UnitCustomPipeline.vue
- manifests/experiences/netflix/pipeline.js
- manifests/experiences/tracker-control/pipeline.js
- manifests/experiences/twitter/pipeline.js
- manifests/experiences/uber/pipeline.js
- manifests/generic-pipelines.js
Custom pipelines need various arguments, but most of the time not all of them. This PR allows a custom pipeline function to get the parameters it needs without caring about the order. It should be a bit less error-prone, especially if we add/remove some arguments in the future
> refactor: change custom pipeline arguments

- manifests/experiences/facebook/facebook.json
- manifests/experiences/facebook/pipeline.js
- manifests/experiences/google/google.json
- manifests/generic-pipelines.js
- manifests/jsonToTableSchema.js
This PR is related to https://github.com/hestiaAI/hestialabs-experiences/issues/385 and https://github.com/hestiaAI/hestialabs-experiences/issues/349
Added a new type of pipeline based on accessors. We can create experiments by specifying : 
- a regex to match a set of files: `fileAccessorRegex`
- a jsonPath to access a set of elements in those files: `nodeAccessor`
- a jsonPath for each value/column in those elements: `field`
Here is an example we use for Facebook: 
```
{
"key": "customAudience",
"customPipeline": "jsonToTableConverter",
"customPipelineOptions": { 
"rootAccessor": {
"fileAccessorRegex": "/ads_information/advertisers_using_your_activity_or_information.json",
"nodeAccessor": "$.custom_audiences_all_types_v2[*]"
},
"properties": [
{
"name": "Advertiser",
"field": …
```
> feat: table experience and custom audience view (facebook)

- components/unit/consent-form/SelectFilesDialog.vue
- components/unit/consent-form/UnitConsentForm.vue
- components/unit/consent-form/UnitConsentFormSection.vue
- components/unit/file-explorer/UnitFileExplorer.vue
- config/config.json
- vuetify.options.js
Changes: As described in #350, **except** for the following:
- The file content can still be browsed because it will soon be necessary for selecting individual data points. However, the file hierarchy is shown by default and clicking on a file doesn't automatically switch to this panel.
- I think that clearing the selection when the user unchecks the box would be a very frustrating experience (easy to misclick). Instead, there is a "Clear selection" button inside the dialog. The checkbox is automatically unchecked when clicking this button.
Note: the dialog has been moved to a separate component
> style: update file selection in consent form

- components/TheDataExperience.vue
- components/unit/consent-form/SelectFilesDialog.vue
- components/unit/consent-form/UnitConsentFormSection.vue
- components/unit/file-explorer/UnitFileExplorer.vue
- pages/import.vue
Addresses the following comments (via signal):
- why is the popup so wide? I have massive amounts of whitespace at right. Could the width be dynamically decided?
- it feels odd that the file explorer is a separate frame 'within' the select files dialog. any way to make it a bit more integrated?
- File explorer title not needed here.
- As discussed in #350 the details panel and < arrow should be hidden. This dialog should ONLY be for selecting files. Let's not incorporate any of #366 solution into this, that would probably be a separate dialog.
- Editing your selection is a bit weird. I think it would be better if "2 selected" was a link to trigger the dialog (without changing the checkbox).
The last point lets us work around a bug where the "Select files" button did not appear in the …
> Improvements and bug fix for file selection

- components/base/BaseSearchBar.vue
- components/unit/file-explorer/viewer/UnitFileExplorerViewerCsv.vue
- components/unit/file-explorer/viewer/UnitFileExplorerViewerJson.vue
- components/unit/filterable-table/UnitFilterableTableFilter.vue
- package-lock.json
- package.json
- utils/file-manager.js
- utils/json.js
- utils/json.worker.js
Part of #347 
Changes:
- Add base search bar component
- Display filters in CSV viewer
- Add filter for JSON viewer
Note: there was a feature of `itemifyJSON` that caused objects or array containing only one element to be shrunk into a single node. I removed it, because if we keep it, it often creates elements with too much text that goes out of frame:
Also, it can be confusing to have elements that dynamically move in the hierarchy. But it may be better to put back this feature and solve the problem differently.
> JSON content search

- components/CodeEditor.vue
- components/TheDataExperience.vue
- components/unit/UnitCustomPipeline.vue
- components/unit/file-explorer/viewer/UnitFileExplorerViewerJson.vue
- manifests/experiences/facebook/facebook.json
- manifests/generic-pipelines.js
- manifests/generic-pipelines.test.js
- manifests/jsonToTableSchema.js
- nuxt.config.js
- package-lock.json
- package.json
- pages/import.vue
- utils/accessor.js
- utils/accessor.test.js
- utils/file-manager-mock.js
- utils/file-manager-workers.js
- utils/file-manager.js
- utils/file-manager.test.js
- utils/json.js
- utils/json.test.js
- utils/utils.js
Any pipeline that has custom options gets a switch called "Edit options" next to the run button. Switching it on opens an editor for the options. The pipeline can be run again with the modified options. This adresses most of #400
I didn't have time to add the relatively similar functionality of displaying a table when the user clicks a node in the json viewer #408. I got as far as adding a jsonPath to every item displayed in the tree view.
> Feat: edit, test modification of custom pipeline options

- components/unit/consent-form/ShowFilesDialog.vue
- components/unit/consent-form/UnitConsentFormSection.vue
- pages/import.vue
#417
- Automatically check the "individual files" checkbox if files are included in the zip
- Add a dialog on import for viewing the list of included files
> fix: missing checkbox for old exported zips

- components/TheAppBar.vue
- components/unit/file-explorer/UnitFileExplorer.vue
#407
The table header no longer goes over the navigation drawer. I did it by setting the z-index attribute.
At the same time, I'm suggesting to put the summary string in an expandable panel, as illustrated below, because it can take a lot of screen space. It is open by default, and the user can close it when they start exploring the files content.
We can revert this commit if you don't like it
> fix: z-index issues

- components/TheDataExperience.vue
- components/unit/UnitQuery.vue
- components/unit/UnitSparql.vue
- components/unit/consent-form/UnitConsentForm.vue
- components/unit/consent-form/UnitConsentFormSection.vue
- config/config.json
- pages/import.vue
- store/index.js
Put the results in the store instead of passing them to a sibling component via events and props (`UnitQuery` -> `TheDataExperience` -> `UnitConsentForm`).
Vuex detected that some d3 graphs modify the result objects (e.g. `CharViewSearchSunburst`), so I cloned them before passing them to the graphs.
Also removed some old forgotten code.
I still find the consent form code to be quite messy (especially `UnitConsentFormSection`) but I'm not sure how it could be improved.
> refactor: results passed to consent form

- components/unit/file-explorer/UnitFileExplorer.vue
#384 and #383
current mapping:
```
'audio file': ['mp3', 'm4a', 'wav', 'aac', 'webp'],
'image file': ['jpg', 'jpeg', 'png', 'gif', 'bnp'],
'video file': ['avi', 'mov', 'mp4', 'mpg'],
document: ['pdf', 'html', 'doc', 'docx', 'rtf', 'odt'],
spreadsheet: ['xls', 'xlsx', 'ods'],
'archive file': ['zip', '7z', 'rar', 'gz'],
'data file': ['json', 'csv', 'tsv', 'xml'],
'text file': ['txt', 'md']
```
Feel free to suggest more
> feat: groups of file extensions in summary

- components/chart/ChartView.vue
- components/chart/view/ChartViewGenericDateViewer.vue
- components/chart/view/ChartViewOverviewNetflix.vue
- components/chart/view/ChartViewOverviewTwitter.vue
- components/chart/view/ChartViewOverviewUber.vue
- components/chart/view/ChartViewSankey.vue
- components/chart/view/ChartViewSunburst.vue
- components/chart/view/ChartViewTimeSeries.vue
- components/chart/view/ChartViewTimedObservationsViewer.vue
- components/chart/view/ChartViewTopRow.vue
- components/chart/view/ChartViewTrackerControl.vue
- manifests/experiences/facebook/facebook.json
- manifests/experiences/twitter/twitter.json
- Added a new chart for top-k bar charts to replace the old vega one. You can test it on the Twitter experience (top advertiser) : 
- Fixed several issues we had with overlapping styles between graphics using <style scoped>, this introduced a lot of problems with tooltips but they should all be fixed with this PR. Note that for style inside SVG content we need to prefix them with ```::v-deep``` otherwise they are not applied when used with <style scoped>.
> feat: top row graph + scoped style for all graphs

- utils/csv.js
Closes #372 
Fixes:
- tab-separated tables are now loaded correctly (same for ;-separated-values)
- small optimization of logic
- if a table contains only headers, they are correctly returned
> fix: tab-separated tables and ;-separated tables are now correctly supported

- components/unit/file-explorer/viewer/UnitFileExplorerViewerTxt.vue
#373
It adds a selector to switch between plaintext, JSON, or CSV mode when viewing a  `.txt` file
> feat: txt viewer switch to json or csv

- utils/json.js
The latest refactoring on `UnitFilterableTable` broke the XLSX viewer
Related to #411
> fix: xlsx crash

- manifests/experiences/twitter/__tests__/database.test.js
- manifests/experiences/twitter/__tests__/samples.helpers.js
- manifests/experiences/twitter/database.js
- utils/sql.js
Some users have data with ads that don't have an `impressionTime`. This was causing an error when inserting the values into the database, because we didn't properly replace `undefined` values with `null`
I've fixed the bug and added a new test that checks for these cases.
> fix: undefined values in twitter sql

- components/TheDataExperience.vue
- components/unit/UnitSummary.vue
- components/unit/file-explorer/UnitFileExplorer.vue
- store/index.js
Addresses #364 and #466 
Changes:
- moved the summary to a dedicated tab (the first one)
- clicking a file in the summary brings you to the file explorer tab with the correct file selected
- moved `FileExplorer`'s selected file to vuex store
> feat: put summary in a dedicated tab. clicking files opens explorer

- components/unit/file-explorer/viewer/UnitFileExplorerViewerJson.vue
- utils/file-manager.js
- utils/json.js
- utils/json.test.js
- utils/json.worker.js
The original itemifyJSON was hard enough for me to understand that I didn't see how to fix some bugs.
The rewritten version is hopefully easier to understand also for other people than  myself.
Two minor bugs were fixed in the process:
- missing icon in the json viewer for empty objects/lists
- item ids were not unique
The old function is still there under the name **itemifyJSONOld**
If you need to go back quickly to the old functionality, call itemifyJSONOld instead of itemifyJSON in [json.worker.js](https://github.com/hestiaAI/hestialabs-experiences/blob/master/utils/json.worker.js)
> refactor: rewrite itemifyJSON

- components/TheDataExperience.vue
- manifests/experiences/facebook/database.js
- manifests/experiences/facebook/facebook.json
- manifests/experiences/twitter/__tests__/database.test.js
- manifests/experiences/twitter/database.js
- manifests/experiences/twitter/twitter.json
- manifests/experiences/uber/pipeline.js
- manifests/experiences/uber/uber.json
- utils/file-manager.js
Partly address #353 
Now the files that are required in a zip archive can be defined as globs. 
The Twitter and Facebook pipelines are adapted so that the files that we process can be at any depth in the archive.
Note that the preprocessing also had to be adapted for more flexibility, now it can also use globs. Close #479
I'm not sure if we should still show to the user the list of files that are required (#480). It may give the impression that we are only using these files, while in practice we are using all those that we can process (in the generic date/location viewer). In my opinion, it would be more informative to give this information in each experience (i.e. show "this experience uses the files ad-impressions.js and ad-engagements.js", somewhere not too visible).
> feat: relaxed file restrictions

- components/TheDataExperience.vue
- components/unit/file-explorer/UnitFileExplorer.vue
- store/index.js
These are tentative fixes for crashes that I couldn't reproduce reliably. I'm not sure if every change is really needed, but it seems to fix (or at least reduce) the crashes. I don't have time to look at it more carefully because it should be merged quickly for the deep dives.
The crashes happened mostly in the File Explorer, when you had already opened files in another company (e.g. Tinder) and you go to another one (e.g. Tracker Control). It seems that the file manager and the store were left in a dirty state
> fix: random crashes

- components/unit/filterable-table/UnitFilterableTable.vue
- utils/dates.js
- utils/json.js
This PR is related to #375 
Add date translation feature to json viewer + improve code quality + improve date detection in both tables and json viewers.
To detect dates we try to convert the value with the Javascript Date constructor, we check if this result gives a valid date and then to make sure it is not a timestamp in seconds we check that the year is not 1970 (starting year of UNIX timestamps). If all checks pass, we transform the date into a local date string format, otherwise we return the value unchanged. This solution will fail only for dates from 1970, but this does not represent many use cases for us.
> fix: convert timestamps to date strings in json viewers + improve date detection

- components/TheAppBar.vue
- components/TheDataExperience.vue
- components/base/button/BaseButton.vue
- components/base/button/BaseButtonShare.vue
- components/unit/UnitQuery.vue
- components/unit/UnitSummary.vue
- components/unit/consent-form/UnitConsentForm.vue
- components/unit/file-explorer/UnitFileExplorer.vue
- layouts/default.vue
- pages/_key.vue
- pages/index.vue
- vuetify.options.js
This PR is related to #511 and apply the following changes: 
- make the whole experience page as tabs
- remove the shadow effect from the sub-experience cards
- display the newsletter as a disposable alert (and in the footer)
- make the share button at a fixed position. 
- Add title experiences in the app top bar
Demo: 
A lot can be done to improve the UI/UX, this is just a first step.
Now that the size of the sub-experience containers has changed, we need to improve the rendering of each sub-experience, but this could be done in separate issues.
> fix: UI refactoring

- components/chart/view/ChartViewOverviewTwitter.vue
- components/unit/filterable-table/UnitFilterableTable.vue
This PR is related to #514.
To improve the graph's ability to explore different combinations of targeting criteria against advertisers, I have added a search function in the Twitter overview for targeting criteria, advertiser and targeting value. 
This way, a user can, for example, search for any targeting value that are not already displayed on the top 10 and see which advertiser uses that targeting criteria and vice versa. See the example below: 
In addition, I have added to the table the ability to attach a formatter for each column, this is used in TwitterOverview to convert engagement values 0 and 1 to 'Yes' or 'No'.
> feat: add text filtering for targeting criteria and company in Twitter overview

- components/unit/UnitPipelineCustom.vue
- components/unit/UnitPipelineSparql.vue
- components/unit/UnitPipelineSql.vue
- components/unit/UnitQuery.vue
- manifests/experiences/google/google.json
- manifests/generic-pipelines.js
- manifests/index.js
Close #448
Related to #480
Now that we can edit custom pipelines options, it really makes sense to put the google `timedObservationsViewer` in the `customPipelineOptions` instead of having it at the root of the manifest. Thanks to this, custom pipelines no longer need to pass the entire manifest.
I also added file indications for this experience.
Finally, I improved the error handling for all the pipelines. Now, if an unexpected problem occurs, it will show an error message to the user.
> fix: google my activity

- components/chart/view/ChartViewHeatMapHour.vue
This PR is related to #638.
Instead of manually calculating the ticks, we use the d3 scale.ticks method, if the number of ticks chosen is less than the extent, it should still display nice integer ticks. 
I also corrected the position computation of the legend.
> fix: legend spacing + number of ticks using d3

- manifests/experiences/twitter/__tests__/database.test.js
- manifests/experiences/twitter/twitter.json
- manifests/validate-database-config.js
- utils/sql.js
- utils/sql.test.js
* add new primaryKey property
* AUTOINCREMENTED not recommended by SQLite. Instead, declare an INTEGER column as PRIMARY KEY and that column will be an alias for the implicit 'rowid' auto-incremented column. See https://www.sqlitetutorial.net/sqlite-autoincrement/. Side note that explains why we need such a column for foreign key references and cannot use rowid directly in SQLite: "The parent key must be a named column or columns in the parent table, not the [rowid](https://www.sqlite.org/lang_createtable.html#rowid)." ref: https://www.sqlite.org/foreignkeys.html. Currently, only the Twitter experience uses this feature.
* update JSON schema
* fix tests
> fix: add primaryKey property

- components/chart/view/ChartViewOverviewLinkedinConnection.vue
- components/chart/view/ChartViewOverviewNetflix.vue
- components/chart/view/ChartViewOverviewUber.vue
- components/chart/view/ChartViewTimeSeries.vue
- components/chart/view/LinkedinAdTargeting.vue
- components/chart/view/ListLinkedinInference.vue
- utils/csv.js
A bug was introduced when forcing CSVs headers to be in pascalCase, The transformation was only made on the values and not the headers. This makes the DataValidator fails. After fixing it I had to adapt Uber, Netflix, Her and Linkedin experiences accordingly.
> fix: csv naming convention

- experiences/components/TheDataExperience.vue
- experiences/components/__tests__/TheDataExperience.test.js
- experiences/components/unit/UnitQuery.vue
- experiences/config/dev.json
- experiences/i18n-messages-default.json
- experiences/plugins/injected.js
- packages/lib/pipelines/generic-messages.json
- packages/packages/explorer/src/index.ts
Reading the code, I had really a hard time understanding from where some of the translations came, particularly where the **tetv** function was used. 
I think I understood why it was there and did some refactoring to make things more explicit. 
I moved the messages for the generic viewers back to packages where the blocks are defined, and deleted them from i18n-messages-default.json.
And I deleted **tetv**
> Simplify i18n slightly

- experiences/components/chart/view/ChartViewGenericMap.vue
> remove translation of headers in kepler config since it relies on raw names

- experiences/components/unit/UnitKepler.vue
Ensure kepler embedded div uses all available width, not a lesser default width that was being specified. 
Fixes #1095.
> Add automatic width for kepler embeds, to remove white box

- packages/packages/uber/src/kepler-config.ts
In order to make journey arcs easier to see (especially against maps including green parkland), this change was made.
Fixes #1041.
> Change Journey Arcs to a dark green, and a thicker, less opaque line

- experiences/components/unit/UnitQuery.vue
- packages/lib/types/view-block.ts
- packages/packages/uber-driver/package.json
- packages/packages/uber-driver/src/blocks.ts
This issue is related to #1127 and #1115.
Added two parameters in the experience config, a viewBlock can now have the following two attributes: 
`image`: (string) given an URL, insert an image below the `description` field.
`overlay`: (string) Given a message, add an overlay to the entire content of the tab, displaying that message.
> feat: add ability to insert an image in a tab + overlay message in case of future features
