nuxt.config.js, utils/unzip.js
=> fix: unzipit web workers (#56)

components/UnitSparql.vue
=> Fix binding in sparql editor

components/TheDataExperiencePower.vue, components/UnitSparql.vue
This refactoring will be useful for the default view
=> Put vega related code out of UnitSparql

components/TheDataExperienceDefault.vue, components/UnitSparql.vue, manifests/experiences/tinder/tinder.json, utils/sparql.js
Now a query is run, and the graphs are shown.
Only compatible with Tinder at the moment.
=> Complete default view

components/TheDataExperience.vue, components/TheDataExperiencePower.vue, components/UnitVegaViz.vue, manifests/csv-processors.js, manifests/experiences/twitter-workshop/examples/main/sunburst-targeting.vega, manifests/experiences/twitter-workshop/twitter-workshop.json
Add a step in the pipeline, after the SPARQL SELECT and before the visualization
=> CSV processing

components/TheDataExperience.vue, components/TheDataExperienceDefault.vue, components/TheDataExperiencePower.vue, components/UnitQuery.vue, components/UnitQueryResults.vue, components/UnitSparql.vue, manifests/experiences/tinder/tinder.json, manifests/experiences/twitter-workshop/twitter-workshop.json
Here's a first draft of what the default view will look like. The visuals will change but most of the elements are there.
=> WIP: default view

components/TheDataExperience.vue, components/TheDataExperienceDefault.vue, components/UnitQuery.vue, components/UnitQueryResults.vue, components/UnitSparql.vue, manifests/experiences/tinder/tinder.json, manifests/experiences/twitter-workshop/examples/main/all-advertisers.rq, manifests/experiences/twitter-workshop/examples/main/select-targeting-criteria.rqx, manifests/experiences/twitter-workshop/twitter-workshop.json
Various UI improvements and text description
=> Improved default view

components/TheDataExperienceDefault.vue, components/UnitFiles.vue, utils/rdf.js, utils/unzip.js
=> fix: crashes and loops on wrong input files

components/TheDataExperienceDefault.vue, components/UnitCustomPipeline.vue, components/UnitQuery.vue, manifests/experiences/twitter/pipeline.js, manifests/experiences/twitter/twitter.json, pages/import.vue, utils/aggregate.js, utils/rdf.js
Replaced sparql pipelines by custom pipelines. It's already much better, but ultimately we want to use the SQL pipeline in this case, because with custom pipelines we are processing the same file multiple times in a similar way.
The small sample now takes less than 10s to run, and the big takes ~2min. To further improve this I wanted to launch every pipeline in a separate web worker, but we cannot pass functions in web worker messages and I don't know how to work around this problem.
Close #199
=> Improve Twitter performance

pages/import.vue
Close https://github.com/hestiaAI/digipower-data-experiences/issues/33
Close https://github.com/hestiaAI/digipower-data-experiences/issues/34
=> fix: error handling on import page

components/graphs/Sunburst.vue, manifests/experiences/google/google.json, manifests/generic-pipelines.js, manifests/index.js, manifests/parsers.js, utils/file-manager.js
Added a watch for values update: 
`watch: {
values() {
this.drawViz()
}
}`
And remove previous svg before creating one with: 
`d3.select('#' + this.graphId + ' svg').remove()`
=> fix: issue #219

components/unit/UnitQuery.vue, manifests/experiences/facebook/postprocessors.js, manifests/experiences/twitter/postprocessors.js, pages/import.vue, utils/sql.js
There were errors on the twitter experience when the user inputs an advertiser that doesn't exist in the data. Now the page shows "No relevant data found".
=> fix: better handling of cases where no data is found

components/the-experience-menu/TheExperienceMenu.vue, components/unit/consent-form/UnitConsentForm.vue, components/unit/consent-form/UnitConsentFormSection.vue, config/README.md, config/config.json, config/tfac.json
Setup of the form as described in  #237
=> feat: Tracking-Free Ads Coalition consent form

components/chart/view/ChartViewOverviewUber.vue, components/chart/view/ChartViewTrackerControl.vue, manifests/experiences/uber/uber.json
Some updates on the uber experience, mainly the overview graph made clearer.
=> feat: Uber overview v2

components/chart/view/ChartViewSearchSunburst.vue, components/chart/view/ChartViewSunburst.vue, manifests/experiences/twitter/twitter.json
New component for the Twitter experience, allowing users to search for an advertiser in a table and display the corresponding sunburst on click.
=> feat: Search sunburst

components/chart/view/ChartViewGenericDateViewer.vue
Address the following issues:
- https://github.com/hestiaAI/digipower-data-experiences/issues/63
- https://github.com/hestiaAI/digipower-data-experiences/issues/64
- https://github.com/hestiaAI/digipower-data-experiences/issues/80
=> fix: #63, #64, #80

components/unit/consent-form/UnitConsentForm.vue, components/unit/consent-form/UnitConsentFormSection.vue, config/README.md, config/config.json, config/digipower.json, config/tfac.json
- Digipower consent form
- Multiline text areas
- Movable and customizable data section
- Refactoring
Implement https://github.com/hestiaAI/digipower-data-experiences/issues/86
=> feat: digipower consent form and various form improvements

components/unit/file-explorer/UnitFileExplorer.vue, components/unit/file-explorer/viewer/UnitFileExplorerViewerUnknown.vue
This covers https://github.com/hestiaAI/digipower-data-experiences/issues/79 in part.
It allows to look at or download files of a type for which we have no specific viewer. It doesn't help in case a specific viewer fails.
=> feat: file viewer for unkown types

manifests/experiences/signal/signal.json, manifests/index.js
=> fix: added checker for property key in defaultView, added key to signal manifest

components/chart/view/ChartViewGenericDateViewer.vue, components/chart/view/ChartViewTrackerControl.vue, vuetify.options.js
Address the following issue: https://github.com/hestiaAI/digipower-data-experiences/issues/69
Add a multiple select button to filter files + typo in TC experience
=> feat: add ability to focus on specific files in dated event viewer

components/unit/consent-form/UnitConsentForm.vue
It's now clearer what required data is missing for sending the form
=> feat: show missing data

components/unit/consent-form/UnitConsentForm.vue, components/unit/consent-form/UnitConsentFormSection.vue, config/README.md, config/config.json, config/digipower.json
Close https://github.com/hestiaAI/digipower-data-experiences/issues/89
Close https://github.com/hestiaAI/digipower-data-experiences/issues/90
=> feat: consent form updates

components/chart/view/ChartViewTrackerControl.vue
Related to https://github.com/hestiaAI/digipower-data-experiences/issues/84
Add select to only show a subset of apps in TC experience, allowing the use of certain applications to be hidden if the user wishes to share their data/viz
=> feat: Add select to only show a subset of apps in TC experience

components/chart/ChartView.vue, components/unit/UnitQuery.vue, components/unit/consent-form/UnitConsentForm.vue, manifests/README.md, manifests/experiences/apple/apple.json, manifests/experiences/bookbeat/bookbeat.json, manifests/experiences/facebook/facebook.json, manifests/experiences/finnair/finnair.json, manifests/experiences/gigantti/gigantti.json, manifests/experiences/google/google.json, manifests/experiences/helsingin-sanomat/helsingin-sanomat.json, manifests/experiences/hsl/hsl.json, manifests/experiences/k-ryhma/k-ryhma.json, manifests/experiences/lime/lime.json, manifests/experiences/linkedin/linkedin.json, manifests/experiences/netflix/netflix.json, manifests/experiences/s-ryhma/s-ryhma.json, manifests/experiences/signal/signal.json, manifests/experiences/spotify/spotify.json, manifests/experiences/tinder/tinder.json, manifests/experiences/tracker-control/tracker-control.json, manifests/experiences/twitter/twitter.json, manifests/experiences/uber/uber.json, manifests/experiences/voi/voi.json, manifests/experiences/whatsapp/whatsapp.json, manifests/experiences/wolt/wolt.json, pages/import.vue
- Refactor visualizations: each block now contains 0 or 1 viz, instead of 0 or more (it wasn't useful).
- Can now define props for visualizations in the json config
=> feat: generic viz support

utils/json.js
This is part of the improvement of the performance of the generic file explorer, more specifically the json viewer:
- (https://github.com/hestiaAI/digipower-data-experiences/issues/66)
Right now, we always group elements of a big list into groups of 50. If a list has 100000 elements, then we will have 100000 / 50 = 2000 groups, all at the same level.
The new version creates groups of 10 elements across each level, as you can see below.
This causes the expand buttons to react a lot faster to clicks.
=> performance: json viewer is now faster and recursively groups elements of a long list together

README.md, components/unit/filterable-table/__tests__/UnitFilterableTable.test.js, components/unit/filterable-table/__tests__/__snapshots__/UnitFilterableTable.test.js.snap, jest.setup.js, package-lock.json, package.json
Changes:
- Fixed a bug that caused some tests to fail (`RegeneratorRuntime` error)
- Added an example snapshot test
- Updated the README with some documentation about testing, the TFAC instance, and changed the overall structure.
Close #185 
Contributes to #191
=> feat: snapshot testing and documentation

components/unit/file-explorer/UnitFileExplorer.vue
https://github.com/hestiaAI/digipower-data-experiences/issues/74
=> fix(file-explorer): close drawer on outside click

components/unit/file-explorer/UnitFileExplorer.vue, components/unit/file-explorer/viewer/UnitFileExplorerViewerCsv.vue, components/unit/file-explorer/viewer/UnitFileExplorerViewerJson.vue, components/unit/file-explorer/viewer/UnitFileExplorerViewerUnknown.vue, components/unit/file-explorer/viewer/mixin-loading.js, components/unit/filterable-table/UnitFilterableTable.vue, manifests/experiences/twitter/database.js, manifests/experiences/twitter/database.worker.js, package-lock.json, utils/csv.worker.js, utils/file-manager.js, utils/json.worker.js, utils/utils.js
- Shows the cursor as an hourglass when it is above the file explorer while a csv or  json file is loading.
- Uses workers to avoid blocking browser rendering, when parsing csv and json files and when building the twitter sql database.
- Removes the options to see all entries of a table on the same page.
[hestiaAI/digipower-data-experiences#67](https://github.com/hestiaAI/digipower-data-experiences/issues/67)
=> feat: hourglass pointer and webworkers

.eslintrc.js, components/unit/filterable-table/UnitFilterableTable.vue
Disable some warnings
Fix something in UnitFilterableTable.
=> fix: linting problems

components/unit/filterable-table/UnitFilterableTable.vue
Related to https://github.com/hestiaAI/digipower-data-experiences/issues/95
=> fix: sticky header for data table + fixed height

manifests/experiences/google/google.json, manifests/experiences/google/pipeline.js
Related to https://github.com/hestiaAI/digipower-data-experiences/issues/109
=> fix: allow multiple files in google experience and add location viewer

manifests/experiences/facebook/database.js, manifests/experiences/facebook/facebook.json, manifests/experiences/facebook/index.js, manifests/experiences/facebook/queries/ad-interactions.sql, manifests/experiences/facebook/queries/advertisers-contact-list.sql, manifests/experiences/facebook/queries/off-facebook-activity-count.sql, manifests/experiences/facebook/queries/off-facebook-activity-type-count.sql, manifests/experiences/facebook/queries/off-facebook-activity.sql, manifests/experiences/facebook/queries/your-topics.sql, manifests/experiences/facebook/visualizations/top-k-advertisers.vega.json
Updated five experiences to work with SQL
=> feat: sql pipeline for facebook

utils/file-manager.js
Replaced unzipit with JSZip
https://github.com/hestiaAI/hestialabs-experiences/issues/332
=> fix: crash when unzipping on chrome

components/unit/UnitCustomPipeline.vue
=> fix: parsing of options in custom pipeline

components/unit/consent-form/UnitConsentForm.vue
=> style: prettify json in exported zip

components/unit/file-explorer/viewer/UnitFileExplorerViewerTxt.vue
=> style: text file viewer

components/chart/view/ChartViewOverviewTwitter.vue
=> style: twitter overview minor changes

components/TheDataExperience.vue, components/UnitSql.vue, components/base/BaseProgressCircular.vue, components/unit/UnitCustomPipeline.vue, components/unit/UnitQuery.vue, components/unit/UnitSparql.vue, components/unit/consent-form/UnitConsentForm.vue, components/unit/file-explorer/UnitFileExplorer.vue, components/unit/filterable-table/UnitFilterableTable.vue, components/unit/mixin-pipeline.js, store/experience.js
=> fix: auto-run subexperiences

components/unit/file-explorer/UnitFileExplorer.vue, utils/file-manager.js
=> feat: hide unnecessary path info in summary

manifests/experiences/apple/apple.json, manifests/experiences/bookbeat/bookbeat.json, manifests/experiences/demdex/demdex.json, manifests/experiences/explorer/explorer.json, manifests/experiences/facebook/facebook.json, manifests/experiences/finnair/finnair.json, manifests/experiences/full-contact/full-contact.json, manifests/experiences/gigantti/gigantti.json, manifests/experiences/helsingin-sanomat/helsingin-sanomat.json, manifests/experiences/hsl/hsl.json, manifests/experiences/k-ryhma/k-ryhma.json, manifests/experiences/lime/lime.json, manifests/experiences/linkedin/linkedin.json, manifests/experiences/netflix/netflix.json, manifests/experiences/s-ryhma/s-ryhma.json, manifests/experiences/sbb/sbb.json, manifests/experiences/signal/signal.json, manifests/experiences/spotify/spotify.json, manifests/experiences/twitter/twitter.json, manifests/experiences/uber/uber.json, manifests/experiences/voi/voi.json, manifests/experiences/whatsapp/whatsapp.json, manifests/experiences/wolt/wolt.json
=> style: replace 'Dated observations' 'Timeline'

utils/file-manager.js, utils/file-manager.test.js
#461 
Tell me if you know other files that should be ignored
=> fix: ignore MacOS tmp files

manifests/experiences/facebook/facebook.json, manifests/experiences/tinder/tinder.json, manifests/experiences/tracker-control/tracker-control.json
=> style: fix tab title overflow

components/unit/UnitIntroduction.vue
Part of #458 (I'm waiting for an answer for the rest)
=> style: add intro text for transparency

components/TheDataExperience.vue
=> fix: show error message for encrypted zip

components/SettingsSpeedDial.vue, components/TheDataExperience.vue, components/__tests__/TheDataExperience.test.js, components/unit/UnitQuery.vue, components/unit/consent-form/SelectFilesDialog.vue, components/unit/consent-form/UnitConsentForm.vue, components/unit/consent-form/UnitConsentFormSection.vue, components/unit/consent-form/__tests__/UnitConsentForm.test.js, components/unit/consent-form/__tests__/consent-form.helpers.js, components/unit/files/UnitFiles.vue, config/README.md, config/config.json, config/tfac.json, pages/import.vue, store/index.js
This is mostly a refactoring of the consent-form components, but there are a few other changes related to the store clearing.
=> refactor: consent form (+small bug fixes)

manifests/experiences/google/google.json
=> fix: my activity files with/without spaces

components/TheDataExperience.vue, components/chart/view/ChartViewOverviewUber.vue, components/chart/view/ChartViewTimeSeries.vue, components/the-experience-menu/TheExperienceMenu.vue, components/the-experience-menu/TheExperienceMenuCards.vue, components/unit/files/UnitFiles.vue, config/workshop.json, manifests/experiences/apple/apple.json, manifests/experiences/explorer/explorer.json, manifests/experiences/facebook/facebook.json, manifests/experiences/google/google.json, manifests/experiences/netflix/netflix.json, manifests/experiences/signal/signal.json, manifests/experiences/spotify/spotify.json, manifests/experiences/tinder/tinder.json, manifests/experiences/tracker-control/tracker-control.json, manifests/experiences/twitter/twitter.json, manifests/experiences/uber/uber.json, manifests/experiences/whatsapp/whatsapp.json
Made the change needed in #582.
Add ability to hide summary and file explorer from an experience.
=> fix: i582, UI/UX fixes

components/chart/view/ChartViewAreaTop.vue, components/chart/view/ChartViewLinePieTop.vue, components/chart/view/ChartViewOverviewInstagramMessage.vue, utils/type-check.js
Add 4 new visualisations to instagram experience.
=> feat: instagram experience

package-lock.json, package.json
All deployments are broken because by default webpack 5 is installed instead of webpack 4, you have to install webpack 4 explicitly.
=> fix: broken deployment, webpack version

components/unit/consent-form/UnitConsentForm.vue, components/unit/consent-form/__tests__/UnitConsentForm.test.js, pages/import.vue, store/index.js
=> feat: add experience version to data upload (#358)

experiences/components/TheAppBar.vue, experiences/config/README.md, experiences/config/barebones.json
https://github.com/hestiaAI/project-planning/issues/9
=> feat: enable external home link

experiences/components/TheAppBar.vue, experiences/components/base/card/BaseBubbleCard.vue, experiences/config/dev.json, experiences/config/digipower-academy.json, experiences/pages/index.vue, packages/package-lock.json
This PR is related to #951.
Also improve image display on bubble cards.
Minor fix on homepage text.
Update packages version.
=> feat: add new bubble for sciences Po

experiences/components/TheBubbleMenu.vue, experiences/components/base/card/BaseTwitterCard.vue, experiences/config/README.md, experiences/config/dev.json, experiences/config/digipower-academy.json, experiences/pages/index.vue
=> feat: add parameter to show bubbles on homepage 

.vscode/settings.json, experiences/components/base/button/BaseButton.vue, experiences/components/base/button/BaseButtonShare.vue, experiences/components/chart/view/ChartViewGenericMap.vue, experiences/components/chart/view/ChartViewGoogleOnePlace.vue, experiences/components/chart/view/ChartViewSankey.vue, experiences/config/dev.json, experiences/config/digipower.json, experiences/i18n/en.json, experiences/i18n/fr.json, experiences/layouts/default.vue, experiences/mixins/page.js, experiences/nuxt.config.js, experiences/pages/bubble/_bubble/experience/_experience/index.vue, experiences/pages/bubble/_bubble/index.vue, experiences/pages/experience/_experience/index.vue, experiences/pages/index.vue, experiences/pages/login.vue, experiences/plugins/i18n.js, experiences/store/index.js, experiences/utils/utils.js, packages/packages/google/src/messages.json, packages/packages/uber/src/messages.json
=> fix(i18n): progress

experiences/.eslintrc.js, experiences/components/TheDataExperience.vue, experiences/components/chart/view/ChartViewGenericDateViewer.vue, experiences/components/chart/view/ChartViewSearchSunburst.vue, experiences/components/chart/view/ChartViewSunburst.vue, experiences/components/chart/view/dc/mixin.js, experiences/components/chart/view/mixin.js, experiences/components/unit/UnitDownload.vue, experiences/utils/sql.js
=> perf(experiences): profile perf of pipeline (#1011)

experiences/utils/sql.js
This reverts commit 6dcb56e026cbf261e4c5ec0532a0fa49a9480697.
Valentin didn't have time to do it himself
=> Revert "refactor(experiences): simplify prepared statement construction"

experiences/components/unit/files/UnitFiles.vue
Related to #1048.
Convert files read by Uppy to new File API BrowserFile.
=> fix: broken Zip read

packages/packages/netflix/src/messages.json
Fixes #1108. 
Tested locally in English and French, works. 
Not tested in a deployment yet.
=> Adding portal link and instructions for Netflix 

experiences/config/digipower-academy.json
good to be deployed; tested two-bubble flow locally and confirming now that bubble server is updated with the new bubble configs.
=> adding tamedia bubble

data-experience/src/components/TheDataExperience.vue, experiences/pages/index.vue, packages/lib/index.ts, packages/lib/types/experience-options.ts, packages/packages/experiences/uber-driver/src/blocks.ts, packages/packages/experiences/uber-driver/src/index.ts, packages/packages/experiences/uber-driver/src/kepler/kepler_config_points.ts, packages/packages/experiences/uber-driver/src/messages.json, packages/packages/experiences/uber-driver/src/postprocessor.ts
-  add config parameter to hide tabs if the needed files are not present
-  add new tabs compatible with portal data
-  add testimonial
=> Update Uber driver experience + new config parameter

data-experience/package-lock.json, data-experience/src/components/base/button/BaseButtonDialog.vue, data-experience/src/main.js, experiences/components/base/BaseButton.vue, experiences/pages/france/uber.vue, experiences/pages/uber.vue, package-lock.json, packages/package-lock.json
Add Custom Upload form linked to our OVH S3 bucket.
Add verification for the given archive, encryption and upload mechanism
Fix an issue with decrypt file feature on experiences
=> feat: uber upload

experiences/components/CheckoutDialog.vue, experiences/components/FileUploader.vue, experiences/pages/france/uber.vue, experiences/pages/uber/switzerland.vue
Add a progression bar when uploading files + redirect user automatically to the payment page.
=> feat: redirect upload + progression of upload

experiences/components/FileUploader.vue, experiences/components/base/BaseButton.vue, experiences/config/uploads-config.json, experiences/pages/france/uber.vue, experiences/plugins/init.js, experiences/store/index.js, experiences/utils/fileHelpers.js
Add a link to horkos deluxe on uber page
Parametrize the file explorer with a configuration file
Add phone number infos
=> feat: horkos deluxe

experiences/utils/pdio-wiki.js
T'as seulement besoin d'appeler la dernière fonction du fichier: fetchDataControllerEmails
Si tu ne donnes pas d'argument, ça te retourne toutes les compagnies
=> pdio sparql client
